export const REQUEST_FACEBOOK_LOGIN = "REQUEST_FACEBOOK_LOGIN";
export const REQUEST_FACEBOOK_LOGIN_FAILURE = "REQUEST_FACEBOOK_LOGIN_FAILURE";
export const REQUEST_PHONE_NUMBER_LOGIN = "REQUEST_PHONE_NUMBER_LOGIN";
export const REQUEST_PHONE_NUMBER_LOGIN_FAILURE =
  "REQUEST_PHONE_NUMBER_LOGIN_FAILURE";
